// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Ym67k1X0Zl8i4Efg6axgTGwXkEfzEV8',
    appId: '1:809916914557:web:0f87d3d4e752932e9c8a14',
    messagingSenderId: '809916914557',
    projectId: 'authan-8aaad',
    authDomain: 'authan-8aaad.firebaseapp.com',
    storageBucket: 'authan-8aaad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYpz_h5ep9-fwGwQdsIYmMnB8uP1UtgQ',
    appId: '1:809916914557:android:91b71c0d8232f7639c8a14',
    messagingSenderId: '809916914557',
    projectId: 'authan-8aaad',
    storageBucket: 'authan-8aaad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Yll7sma0ldoIE8-wh4NGhZ1UpT_WG_0',
    appId: '1:809916914557:ios:fbdccfed2e4b6ac99c8a14',
    messagingSenderId: '809916914557',
    projectId: 'authan-8aaad',
    storageBucket: 'authan-8aaad.appspot.com',
    iosClientId: '809916914557-u6kp16vfre3024hak2j9ehvkfccr1212.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Yll7sma0ldoIE8-wh4NGhZ1UpT_WG_0',
    appId: '1:809916914557:ios:fbdccfed2e4b6ac99c8a14',
    messagingSenderId: '809916914557',
    projectId: 'authan-8aaad',
    storageBucket: 'authan-8aaad.appspot.com',
    iosClientId: '809916914557-u6kp16vfre3024hak2j9ehvkfccr1212.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTestApp',
  );
}
